FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p IvanSemin.com/img && \
    chmod -R 754 /var/www/SeminIvan.com/ && \
    useradd Ivan && groupadd Semin && usermod -aG Ivan Semin && \
    chown -R Ivan:Semin /var/www/IvanSemin.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/IvanSemin/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Ivan/g' /etc/nginx/nginx.conf
ADD index.html /var/www/SeminIvan.com/
ADD img.jpg /var/www/IvanSemin.com/img/
CMD ["nginx", "-g", "daemon off;"]
